# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: flutter doctor
      - run:
          name: Build Application
          command: flutter test
      - store_artifacts:
         path: build/app/outputs/flutter-apk/app-release.apk
  unit-tests:
    machine: true
    steps:
        - checkout
        - run: echo "Running unit tests"

          
